import os
print("AncientOS Incremental Update") 
old_zip=input("Old Path Target : ")
new_zip=input("New Path Target : ")
print("Doing it . . .")
try:
		filecheck=open("generator.sh")
		filecheck.close()
except:
    code="./build/make/tools/releasetools/ota_from_target_files  --block -i old new incremental.zip"
    saveFile2=open("generator.sh",'w')
    saveFile2.write(str(code))
    saveFile2.close()
fin = open("generator.sh", "rt")
data = fin.read()
data = data.replace('old', old_zip)
fin.close()
fin = open("generator.sh", "wt")
fin.write(data)
fin.close()
fin = open("generator.sh", "rt")
data = fin.read()
data = data.replace('new', new_zip)
fin.close()
fin = open("generator.sh", "wt")
fin.write(data)
fin.close()
os.system("chmod a+x generator.sh")
os.system("bash generator.sh")
